In [41]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [1]:
import pickle
with open('rf_model.pkl','rb') as f:
    model=pickle.load(f)

In [3]:
model

RandomForestClassifier(bootstrap=False, max_depth=10, min_samples_split=10,
                       n_estimators=65)

In [39]:
out = model.predict([[10,3,2]])
out

array([4], dtype=int64)

In [ ]:
# 4 -- rated outstanding

In [43]:
model.predict([[15,2.5,4]])

array([2], dtype=int64)

In [ ]:
# 2 -- rated good

In [51]:
model.predict([[8,2,5]])

array([2], dtype=int64)

In [ ]:
# 2 -- rated good

In [83]:
model.predict([[3,1,6]])

array([2], dtype=int64)

In [ ]:
# 2 -- rated good